### PR TITLE
Feature/add srcdir

### PR DESCRIPTION
**Pull request by mike-zipit**
This PR allows shins to be installed in node_modules.

A project may now be bootstrapped by:

```
npm init
npm i --save-dev shins
cp node_modules/shins/source/ . -R
mkdir docs
npx shins --o docs/index.html --srcdir $(pwd)/source source/index.html.md 
```

### CODE REVIEW

**Comment by mike-zipit** [comment]
If somebody could show me the Snyk error, I'll correct the issue

**Comment by MikeRalphson** [comment]
Command Injection

Vulnerable module: shelljs

Introduced through: shelljs@0.8.3

Detailed paths

Introduced through: shins@2.3.2-2 ›shelljs@0.8.3

Overview

shelljs is a portable Unix shell commands for Node.js.
Affected version of this package are vulnerable to Command Injection. It is possible to invoke commands from shell.exec() from external sources, allowing an attacker to inject arbitrary commands.

**Comment by mike-zipit** [comment]
OK, I'll find another way to do a recursive copy with update other than shelljs.

**Comment by mike-zipit** [comment]
OK, I've done the following:

* Removed `shelljs` and replaced with `fs-jetpack`
* Added unit tests using [jest](https://jestjs.io)

I believe this is fully backwards compatible, but I'm not positive of every use case.

**Comment by MikeRalphson** [comment]
Thanks, will pull and test.

**Comment by MikeRalphson** [comment]
I'm a little confused by the comment

> This PR allows shins to be installed in node_modules.

Several projects install `shins` as a dependency in `node_modules` (`openapi-gui`, `shinola`, `make_shins`, `api2html` etc) and as far as I know everything works fine. What is the use-case for installing in `node_modules` and then calling it on the command-line, in preference to installing it globally or using a checked-out git clone?

**Comment by mike-zipit** [comment]
The current version seems to have 2 usage models:

* Use make-shins/api2html and simply modify logo/css
* Clone shins and modify `source`/`pub` directories

This PR adds a 3rd option:

* Install as dependency and substitute your own `source` and/or `pub` directory in it's entirety 

Even if you don't feel this is of use, I think the jest testing is worth reviewing / integrating separately if you choose not to merge the PR.

**Comment by MikeRalphson** [comment]
The main (recommended) usage is to install globally as a CLI. The third party wrappers are unnecessary and outdated.

If this PR makes using shins as a dependency easier, great. 

Would it be a total pain to replace jest with mocha, and expect with should.js? As these are what I use on other projects.

**Comment by MikeRalphson** [comment]
Closing in favour of #59 which seems simpler. Thanks for the PR.

**Pull request closed without merging**
