### PR TITLE
Using markdown-it-attrs with code fences

### PR DESCRIPTION
**Pull request by simondean**
This PR is related to issue https://github.com/Mermade/shins/issues/30

### CODE REVIEW

**Comment by simondean** [comment]
Hi @MikeRalphson.  I was wondering whether this PR would be suitable for including in `shins`.  It provides an implementation/fix for #30.   

The approach the PR takes is based on the following couple of comments: 
* https://github.com/markdown-it/markdown-it/issues/457#issuecomment-389686870
* https://github.com/arve0/markdown-it-attrs/issues/59#issuecomment-386806932

The code I've implemented in the `fence` method of the PR is based on `markdown-it`'s `fence` method in https://github.com/markdown-it/markdown-it/blob/master/lib/renderer.js#L39.  

Let me know if there's any info I can add.  Thanks

**Comment by MikeRalphson** [comment]
Looks good. I just need to find the time to test it doesn't affect the existing output. Thanks for your patience.

**Comment by simondean** [comment]
No worries.  Thanks @MikeRalphson

**Comment by MikeRalphson** [comment]
When comparing the before and after output, I see each of the code blocks differs as per this example:

```diff
-<pre class="highlight tab tab-shell"><code><span class="hljs-comment"># You can also use wget</span>
+<pre><code class="highlight tab tab-shell"><span class="hljs-comment"># You can also use wget</span>
```

Could the `class` attributes be moved back to the `<pre>` element, as some people may be depending on that?

**Comment by ribrewguy** [comment]
I've tried this update, but it doesn't seem to add the style. The linked markdown issue suggests that adding the attributes should be in the form:

```
    ```http {.some-class}
    GET /foo/bar HTTP/1.1
    ...
    ```
```
But that doesn't seem to do anything in the generated code block. I would expect that `class="some-class"` would be added to the pre or code element.

**Comment by MikeRalphson** [comment]
Please re-raise over on [slant](https://github.com/mermade/slant) if still an issue.

**Pull request closed without merging**
